use smallvec::SmallVec;
use std::array;
use std::collections::HashSet;

/// A point in the $n$-dimensional integer lattice.
pub type Pos<const N: usize> = [i8; N];

/// An $n$-dimensional solid object formed by joining
/// $1\times\cdots\times1$ cubies face to face.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct Polycube<const N: usize>(SmallVec<Pos<N>, 5>);

impl<const N: usize> Polycube<N> {
  /// Returns the number of cubies in the $n$-polycube.
  pub fn cubie_count(&self) -> usize {
    self.0.len()
  }

  /// Returns the cubies that form this $n$-polycube.
  pub fn cubies(&self) -> &[Pos<N>] {
    &self.0
  }

  /// Applies a transformation to the $n$-polycube.
  pub fn transform(&self, f: impl FnMut(Pos<N>) -> Pos<N>) -> Self {
    Self(self.0.iter().copied().map(f).collect())
  }

  /// Returns the translate of the $n$-polycube whose cubie
  /// coordinates are nonnegative and as small as possible.
  ///
  /// This shape is called the _aspect_ of the polycube. Section 1.3
  /// of the book [_Tilings and Patterns_][tap] by B. Grünbaum and
  /// G. C. Shephard (1987) discusses the number of distinct aspects
  /// of the tiles in particular classes of tessellations.
  ///
  /// [tap]: https://dl.acm.org/doi/10.5555/19304
  pub fn aspect(&self) -> Self {
    let off: [_; N] = array::from_fn(|i| self.0.iter().map(|p| p[i]).min().unwrap());
    self.transform(|pos| array::from_fn(|i| pos[i] - off[i]))
  }

  /// Returns the set of aspects corresponding to all rotations and
  /// reflections of the $n$-polycube in $n$ dimensions.
  ///
  /// D. E. Knuth called these the _base placements_ of a polycube
  /// in exercise 7.2.2.1-266 of [_The Art of Computer Programming_
  /// **4B**, Part 2][taocp] (Addison-Wesley, 2022).
  ///
  /// [taocp]: https://www-cs-faculty.stanford.edu/~knuth/taocp.html#vol4
  pub fn base_placements(&self) -> HashSet<Self> {
    const { assert!(N >= 2) };
    // The group of symmetries of an $n$-polycube is isomorphic to a
    // subgroup of the rotation group $G_n$ of the $n$-cube, which is
    // generated by the following two elementary transformations:
    // 1. A $90\circ$ turn in the $(x_1,x_2)$ plane:
    //    $(x_1,x_2,x_3\dots,x_n)\mapsto(x_2,x_{\text{max},1}-x_1,x_3,\dots,x_n)$;
    // 2. An orientation-preserving cyclic shift of the axes:
    //    $(x_1,x_2\dots,x_n)\mapsto(x_2,\dots,x_n,x')$ with $x'=x_1$
    //    for odd $n$, and $x'=x_{\text{max},1}-x_1$ for even $n$.
    let ord = (2..=N).product::<usize>() << (N - 1); // of $G_n$.
    let mut visited = HashSet::with_capacity(ord);
    let mut to_visit = Vec::with_capacity(2 * N);
    to_visit.push(self.aspect());
    while let Some(shape) = to_visit.pop() {
      let x_max = shape.0.iter().map(|p| p[0]).max().unwrap();
      let quarter_turn = shape.transform(|mut p| {
        (p[0], p[1]) = (p[1], x_max - p[0]);
        p
      });
      let cyclic_shift = shape.transform(|mut p| {
        let xp = if N % 2 == 0 { x_max - p[0] } else { p[0] };
        p.copy_within(1.., 0);
        p[N - 1] = xp;
        p
      });

      visited.insert(shape);
      for suc in [quarter_turn, cyclic_shift] {
        if !visited.contains(&suc) {
          to_visit.push(suc);
        }
      }
    }
    visited
  }
}

impl<const N: usize, const C: usize> From<[Pos<N>; C]> for Polycube<N> {
  /// Creates an $n$-polycube with $c$ cubies.
  fn from(cs: [Pos<N>; C]) -> Self {
    const { assert!(C > 0, "a polycube has one or more cubies") };
    Self(SmallVec::from(cs))
  }
}

impl<const N: usize> From<&[Pos<N>]> for Polycube<N> {
  /// Creates an $n$-polycube with one or more cubies.
  fn from(cs: &[Pos<N>]) -> Self {
    assert!(!cs.is_empty(), "a polycube has one or more cubies");
    Self(SmallVec::from(cs))
  }
}

impl<const N: usize> From<Vec<Pos<N>>> for Polycube<N> {
  /// Creates an $n$-polycube with one or more cubies.
  fn from(cs: Vec<Pos<N>>) -> Self {
    assert!(!cs.is_empty(), "a polycube has one or more cubies");
    Self(SmallVec::from(cs))
  }
}
